-- Generated by Music Catalog Bootstrap
-- Target engine: mysql
-- Write mode: insert-ignore
-- Required unique key on artist lookup column and release natural key is assumed.

INSERT IGNORE INTO `service_artists` (`name`, `name_key`) VALUES ('Bjork', 'bjork');
INSERT IGNORE INTO `service_artists` (`name`, `name_key`) VALUES ('Radiohead', 'radiohead');
INSERT IGNORE INTO `service_artists` (`name`, `name_key`) VALUES ('My Bloody Valentine', 'my bloody valentine');

INSERT IGNORE INTO `service_releases` (`artist_id`, `title`, `title_key`, `released_on`, `upc`) SELECT `id`, 'Debut', 'debut', '1993-07-05', '5016958997028' FROM `service_artists` WHERE `name_key` = 'bjork';
INSERT IGNORE INTO `service_releases` (`artist_id`, `title`, `title_key`, `released_on`, `upc`) SELECT `id`, 'OK Computer', 'ok computer', '1997-05-21', '724382885229' FROM `service_artists` WHERE `name_key` = 'radiohead';
INSERT IGNORE INTO `service_releases` (`artist_id`, `title`, `title_key`, `released_on`, `upc`) SELECT `id`, 'Loveless', 'loveless', '1991-11-04', '' FROM `service_artists` WHERE `name_key` = 'my bloody valentine';
